---
- hosts: linux_hardening_hosts
  become: yes
  tasks:
    - name: 1. Обновление всех пакетов
      import_tasks: tasks/package_updates.yml

    - name: 2. Настройка SSH
      import_tasks: tasks/ssh_config.yml

    - name: 3. Конфигурация брандмауэра
      import_tasks: tasks/firewall_config.yml

    - name: 4. Настройка прав доступа к файлам
      import_tasks: tasks/file_permissions.yml

    - name: 5. Создание и настройка пользователя
      import_tasks: tasks/user_management.yml

    - name: 6. Установка и базовая настройка nginx
      import_tasks: tasks/nginx_setup.yml

    - name: Бонус. Let's Encrypt сертификаты
      import_tasks: tasks/lets_encrypt.yml